### ISSUE TITLE
No data received

### ISSUE THREAD

**Issue by Oah433** [Zohan/ArduinoCC2500Demo#1]
Hi
I followed your wiring and got two CC2500 devices running your code, however, I am not getting any data on either of them. I edited the code in one of them to have it in Rx state only and I still didnot get data. I had a spectrum analyzer scanning the 2.4 GHz band and still didnot see any transmission spikes. Any ideas?

`

void loop(){

/*
  unsigned long currentMillis = millis();
  if(currentMillis - previousMillis > sendInterval) {
    previousMillis = currentMillis;  
    sendPacket();
  }
  */
  listenForPacket();
}
`

**Comment by NotDevIntended** [comment]
1. What kind of Microcontroller? If Uno/Atmega328p, are you running at 3.3v
   or 5v? Cc2500 needs 3.3v, 5v can cause problems.
2. Check your registers. Especially Iocfg0, iocfg1, and iocfg2. The cc2500
   also has registers you can read to check if a packet has arrived, its
   length, and other details. You can find those in the datasheet.
3. You should plug spectrum analyzer into Tx antenna to see spikes. Also
   spectrum analyzer issues are very difficult to diagnose over email. Most of
   my 2500s transmit at -55dB (very quiet), I have some that go to -36.
4. Send me a picture of the wireless board. If you have one with PA/LNA or
   an amplifier you need to make sure thats being controlled properly.
